version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./DockerFile
    image: trading_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./wagmi/.env
    ports:
      - "8080:8080"
    command: ./wagmi/start.sh

  postgres:
    image: postgres:12
    env_file:
      - ./wagmi/.env

