# Generated by Django 3.2.9 on 2021-12-14 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=24)),
            ],
            options={
                'verbose_name_plural': 'Exchanges',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=24)),
            ],
            options={
                'verbose_name_plural': 'Securities',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=24)),
                ('max_position_size_usd', models.DecimalField(decimal_places=2, default=1000.0, help_text="Maximum position size in USD. A Strategy should weight it's investments as a proportion of this size.", max_digits=9)),
                ('url', models.URLField(verbose_name='endpoint url')),
                ('execute_immediately', models.BooleanField(default=False)),
                ('command', models.CharField(max_length=24)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sizing.exchange')),
            ],
            options={
                'verbose_name_plural': 'Strategies',
            },
        ),
        migrations.CreateModel(
            name='TargetPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(help_text='how many units of the security')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sizing.exchange')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sizing.security')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyPositionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('arrival_price_usd', models.FloatField()),
                ('calculated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sizing.exchange')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sizing.security')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sizing.strategy')),
            ],
        ),
    ]
