# Generated by Django 3.2.4 on 2021-07-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
