# Generated by Django 3.2.9 on 2021-12-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
