# Generated by Django 3.2.9 on 2021-12-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategypositionrequest',
            name='norm_weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
