# Generated by Django 3.2.4 on 2021-07-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizing', '0002_alter_positionrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='max_position_size_usd',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Maximum position size in USD. A Strategy may hold many positions of this size.', max_digits=9),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='name',
            field=models.CharField(db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='security',
            name='name',
            field=models.CharField(db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(db_index=True, max_length=24),
        ),
    ]
