# Generated by Django 3.2.4 on 2021-07-13 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sizing', '0003_auto_20210708_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DesiredPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(help_text='how many stonks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sizing.exchange')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sizing.security')),
            ],
        ),
        migrations.AddField(
            model_name='positionrequest',
            name='desired_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_requests', to='sizing.desiredposition'),
        ),
    ]
