# Generated by Django 3.2.8 on 2021-10-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizing', '0004_auto_20210713_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='command',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
    ]
