# Generated by Django 3.2.8 on 2021-10-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sizing', '0005_strategy_command'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PositionRequest',
            new_name='StrategyPositionRequest',
        ),
        migrations.RenameModel(
            old_name='DesiredPosition',
            new_name='TargetPosition',
        ),
    ]
