# Generated by Django 3.2.8 on 2021-10-30 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sizing', '0006_auto_20211030_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sizing.exchange'),
            preserve_default=False,
        ),
    ]
