# Generated by Django 3.2.8 on 2021-11-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sizing', '0007_strategy_exchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategypositionrequest',
            old_name='size',
            new_name='weight',
        ),
    ]
