# Generated by Django 3.2.8 on 2021-11-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizing', '0008_rename_size_strategypositionrequest_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategypositionrequest',
            name='arrival_price_usd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
