# Generated by Django 3.2.8 on 2021-11-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizing', '0009_strategypositionrequest_arrival_price_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategypositionrequest',
            name='desired_position',
        ),
        migrations.AlterField(
            model_name='targetposition',
            name='size',
            field=models.FloatField(help_text='how many units of the security'),
        ),
    ]
