# Generated by Django 3.2.8 on 2021-11-09 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sizing', '0010_auto_20211101_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategypositionrequest',
            name='calculated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategy',
            name='max_position_size_usd',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text="Maximum position size in USD. A Strategy should weight it's investments as a proportion of this size.", max_digits=9),
        ),
    ]
