# Generated by Django 3.2.8 on 2021-11-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizing', '0011_auto_20211109_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='execute_immediately',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategy',
            name='url',
            field=models.URLField(default='https://api.robotwealth.com/v1/yolo/weights', verbose_name='endpoint url'),
            preserve_default=False,
        ),
    ]
