# Generated by Django 3.2.9 on 2021-12-14 21:25

from django.db import migrations, models
import django.utils.timezone
import execution.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('ioc', models.BooleanField(default=None, editable=False)),
                ('postOnly', models.BooleanField(default=None, editable=False)),
                ('reduceOnly', models.BooleanField(default=None, editable=False)),
                ('liquidation', models.BooleanField(default=None, editable=False)),
                ('size', models.FloatField(default=None, editable=False)),
                ('price', models.FloatField(default=None, editable=False)),
                ('filledSize', models.FloatField(default=None, editable=False)),
                ('avgFillPrice', models.FloatField(default=None, editable=False)),
                ('remainingSize', models.FloatField(default=None, editable=False)),
                ('market', models.CharField(default=None, editable=False, max_length=10)),
                ('side', models.CharField(default=None, editable=False, max_length=4)),
                ('type', models.CharField(default=None, editable=False, max_length=5)),
                ('status', models.CharField(default=None, editable=False, max_length=10)),
                ('clientId', models.CharField(default=None, editable=False, max_length=10)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            bases=(models.Model, execution.models.AuditableMixin),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, execution.models.AuditableMixin),
        ),
    ]
