# Generated by Django 3.2.8 on 2021-12-14 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sizing', '0001_initial'),
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sizing.exchange'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='security',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sizing.security'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.FloatField(default=1, help_text='how many units of the security'),
            preserve_default=False,
        ),
    ]
