# Generated by Django 3.2.9 on 2021-12-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill',
            name='order',
        ),
        migrations.AddField(
            model_name='fill',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='fill',
            name='symbol',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
