# Generated by Django 3.2.9 on 2021-12-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='future',
            field=models.CharField(default=None, editable=False, max_length=10),
        ),
    ]
