# Generated by Django 3.2.9 on 2021-12-15 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_auto_20211215_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='recordedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fill',
            name='clientId',
            field=models.CharField(default=None, editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fill',
            name='future',
            field=models.CharField(default=None, editable=False, max_length=10, null=True),
        ),
    ]
