# Generated by Django 3.2.9 on 2021-12-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0007_auto_20211215_2129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fill',
        ),
    ]
