# Generated by Django 3.2.9 on 2021-12-16 15:39

from django.db import migrations, models
import django.utils.timezone
import execution.models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0008_delete_fill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigIntegerField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('orderId', models.BigIntegerField(editable=False)),
                ('tradeId', models.BigIntegerField(editable=False)),
                ('fee', models.FloatField(default=None, editable=False)),
                ('feeRate', models.FloatField(default=None, editable=False)),
                ('price', models.FloatField(default=None, editable=False)),
                ('size', models.FloatField(default=None, editable=False, null=True)),
                ('feeCurrency', models.CharField(default=None, editable=False, max_length=10)),
                ('future', models.CharField(default=None, editable=False, max_length=10, null=True)),
                ('liquidity', models.CharField(default=None, editable=False, max_length=4)),
                ('market', models.CharField(default=None, editable=False, max_length=5)),
                ('baseCurrency', models.CharField(default=None, editable=False, max_length=10, null=True)),
                ('quoteCurrency', models.CharField(default=None, editable=False, max_length=10, null=True)),
                ('side', models.CharField(default=None, editable=False, max_length=10)),
                ('type', models.CharField(default=None, editable=False, max_length=10)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(models.Model, execution.models.AuditableMixin),
        ),
    ]
