# Generated by Django 3.2.9 on 2021-12-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0009_fill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='future',
            field=models.CharField(default=None, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fill',
            name='liquidity',
            field=models.CharField(default=None, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='fill',
            name='market',
            field=models.CharField(default=None, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='fill',
            name='size',
            field=models.FloatField(default=None, editable=False),
        ),
    ]
