# Generated by Django 3.2.9 on 2021-12-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0010_auto_20211216_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size_delta',
            field=models.FloatField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=None, editable=False, max_length=10),
        ),
    ]
