# Generated by Django 3.2.9 on 2021-12-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0011_auto_20211219_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.BigIntegerField(blank=True, db_index=True, default=None, editable=False, null=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='size_delta',
            field=models.FloatField(blank=True, default=None, editable=False, null=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default=None, editable=False, max_length=10, null=None),
        ),
    ]
