# Generated by Django 3.2.9 on 2021-12-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0012_auto_20211219_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='size_delta',
        ),
    ]
