# Generated by Django 3.2.9 on 2021-12-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0013_remove_order_size_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size_delta',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
