# Generated by Django 3.2.9 on 2021-12-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0015_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
