# Generated by Django 3.2.9 on 2021-12-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0017_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='side',
            field=models.CharField(blank=True, default=None, editable=False, max_length=10, null=None),
        ),
    ]
