# Generated by Django 3.2.9 on 2021-12-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0018_order_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='side',
            field=models.CharField(default=None, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default=None, editable=False, max_length=10),
        ),
    ]
