# Generated by Django 3.2.9 on 2021-12-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0019_auto_20211219_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='created', max_length=10),
        ),
    ]
